### ISSUE TITLE
rails server exited when `docker-compose up`

### ISSUE THREAD

**Issue by zavven** [samtgarson/vueport-example#1]
I use homebrew to install docker:
```
brew cask install docker
```
The docker version is: 1.13.1 (15353)

when I run `docker-compose up`, the rails server exited.
```
web_1      | => Booting Puma
web_1      | => Rails 5.0.0.1 application starting in development on http://localhost:3000
web_1      | => Run `rails server -h` for more startup options
web_1      | A server is already running. Check /opt/tmp/pids/server.pid.
web_1      | Exiting
vueportexample_web_1 exited with code 1
```

**Comment by samtgarson** [comment]
This app by default mounts your local directory into the container, so this can be fixed as a one off by:
```bash
rm tmp/pids/server.pid
```

You shouldn't have to do this every time (or ever again, hopefully)
